version: '2'
services:
  nginx:
    container_name: "nginx"
    image: "nginx"
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/var/www
    ports:
      - 8080:80
      - 80:80
      - 443:443
