version: '2'
services:
  nginx:
    container_name: "jenkins"
    image: "jenkinsci/blueocean"
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8000:8080
      - 50000:50000
